// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// evaluate_design_cpp
List evaluate_design_cpp(int n1, int n, int r1, int e1, int r, double p0, double p1);
RcppExport SEXP _MyTools_evaluate_design_cpp(SEXP n1SEXP, SEXP nSEXP, SEXP r1SEXP, SEXP e1SEXP, SEXP rSEXP, SEXP p0SEXP, SEXP p1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< int >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate_design_cpp(n1, n, r1, e1, r, p0, p1));
    return rcpp_result_gen;
END_RCPP
}
// find_feasible_designs_cpp
DataFrame find_feasible_designs_cpp(double p0, double p1, double alpha, double power, int n_max, int n1_min, bool irrevocable, bool simon);
RcppExport SEXP _MyTools_find_feasible_designs_cpp(SEXP p0SEXP, SEXP p1SEXP, SEXP alphaSEXP, SEXP powerSEXP, SEXP n_maxSEXP, SEXP n1_minSEXP, SEXP irrevocableSEXP, SEXP simonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    Rcpp::traits::input_parameter< int >::type n_max(n_maxSEXP);
    Rcpp::traits::input_parameter< int >::type n1_min(n1_minSEXP);
    Rcpp::traits::input_parameter< bool >::type irrevocable(irrevocableSEXP);
    Rcpp::traits::input_parameter< bool >::type simon(simonSEXP);
    rcpp_result_gen = Rcpp::wrap(find_feasible_designs_cpp(p0, p1, alpha, power, n_max, n1_min, irrevocable, simon));
    return rcpp_result_gen;
END_RCPP
}
// find_admissible_designs_cpp
LogicalVector find_admissible_designs_cpp(IntegerVector n, NumericVector en_null, NumericVector en_alt);
RcppExport SEXP _MyTools_find_admissible_designs_cpp(SEXP nSEXP, SEXP en_nullSEXP, SEXP en_altSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type en_null(en_nullSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type en_alt(en_altSEXP);
    rcpp_result_gen = Rcpp::wrap(find_admissible_designs_cpp(n, en_null, en_alt));
    return rcpp_result_gen;
END_RCPP
}
// evaluate_design_curve_cpp
DataFrame evaluate_design_curve_cpp(int n1, int n, int r1, int e1, int r, NumericVector p_vec);
RcppExport SEXP _MyTools_evaluate_design_curve_cpp(SEXP n1SEXP, SEXP nSEXP, SEXP r1SEXP, SEXP e1SEXP, SEXP rSEXP, SEXP p_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< int >::type e1(e1SEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_vec(p_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(evaluate_design_curve_cpp(n1, n, r1, e1, r, p_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MyTools_evaluate_design_cpp", (DL_FUNC) &_MyTools_evaluate_design_cpp, 7},
    {"_MyTools_find_feasible_designs_cpp", (DL_FUNC) &_MyTools_find_feasible_designs_cpp, 8},
    {"_MyTools_find_admissible_designs_cpp", (DL_FUNC) &_MyTools_find_admissible_designs_cpp, 3},
    {"_MyTools_evaluate_design_curve_cpp", (DL_FUNC) &_MyTools_evaluate_design_curve_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MyTools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
